services:
  - type: web
    name: render-budget-mockup
    runtime: static
    branch: main
    staticPublishPath: .
    previews:
      generation: automatic
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 